version: "3"

services:
  server:
    container_name: "server"
    build:
      context: .
    command: bash -c "python3 manage.py migrate && python3 manage.py test && python3 manage.py create_users && python3 manage.py create_transactions && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
