# Generated by Django 3.2.7 on 2021-09-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
